services:
  postgres:
    image: postgres:15-alpine
    container_name: pokt-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: pokt_portal
      POSTGRES_USER: pokt_user
      POSTGRES_PASSWORD: pokt_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pokt_user -d pokt_portal"]
      interval: 10s
      timeout: 5s
      retries: 5

  hasura:
    image: hasura/graphql-engine:v2.33.4
    container_name: pokt-hasura
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://pokt_user:pokt_password@postgres:5432/pokt_portal
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: pokt_admin_secret
      HASURA_GRAPHQL_JWT_SECRET: '{"type":"HS256", "key":"pokt_jwt_secret_key_for_development_only"}'
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous
      HASURA_GRAPHQL_ENABLE_TELEMETRY: "false"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: pokt-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data_dev:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  pokt-portal:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    environment:
      # Development Environment
      - NODE_ENV=development
      - PORT=3001
      
      # Session Configuration
      - SESSION_SECRET=dev_session_secret_for_cloud_development_only_123456789
      
      # Auth0 Configuration (DISABLED for development)
      - AUTH0_CLIENT_ID=dev_auth0_client_id
      - AUTH0_CLIENT_SECRET=dev_auth0_client_secret
      - AUTH0_DOMAIN=dev.auth0.com
      - AUTH0_AUDIENCE=dev_audience
      - AUTH0_BASE_URL=http://localhost:3001
      - AUTH0_SCOPE=openid profile email
      - AUTH0_SECRET=dev_auth0_secret_for_development
      - AUTH0_ISSUER_BASE_URL=https://dev.auth0.com
      - AUTH0_CONNECTION=Username-Password-Authentication
      
      # Client Environment Variables
      - NOVU_APP_IDENTIFIER=dev_novu_app_identifier
      - PORTAL_API_URL=http://localhost:8080/v1/graphql
      - RELAY_METER_API_URL=http://localhost:3001/mock-meter
      - GOOGLE_ANALYTICS_ID=dev_analytics_id
      
      # Feature Flags - Disable features that require backend
      - FLAG_ENTERPRISE=false
      - FLAG_INFLUX_RELAY_ERROR=false
      - FLAG_LEGACY_MESSAGING=false
      - FLAG_MAINTENANCE_MODE_DASHBOARD=false
      - FLAG_MULTI_LANGUAGE=false
      - FLAG_ANNOUNCEMENT_ALERT=false
      - ANNOUNCEMENT_ALERT_TITLE=dev_announcement_title
      - ANNOUNCEMENT_ALERT_BODY=dev_announcement_body
      - GODMODE_ACCOUNTS=dev_godmode_accounts
      - VERCEL_ENV=development
      - DOCS_STATUS=dev_docs_status
      - FLAG_MAINTENANCE_MODE=false
      - FLAG_STRIPE_PAYMENT=false
      
      # Stripe Environment Variables (DISABLED for development)
      - STRIPE_SECRET_KEY=sk_test_dev_stripe_key
      - STRIPE_WEBHOOK_SECRET=whsec_dev_stripe_webhook
      - STRIPE_PUBLISHABLE_KEY=pk_test_dev_stripe_key
      - STRIPE_PRICE_ID=prod_dev_stripe_price
      
      # Novu Environment Variables (DISABLED for development)
      - NOVU_API_KEY=dev_novu_api_key
      - NOVU_APP_ID=dev_novu_app_id
      
      # Vercel KV Environment Variables (DISABLED for development)
      - KV_REST_API_URL=http://localhost:3001/mock-kv
      - KV_REST_API_TOKEN=dev_kv_token
      - KV_REST_API_READ_ONLY_TOKEN=dev_kv_readonly_token
      
      # Database Configuration
      - DATABASE_URL=postgres://pokt_user:pokt_password@postgres:5432/pokt_portal
      - HASURA_GRAPHQL_ENDPOINT=http://localhost:8080/v1/graphql
      - HASURA_GRAPHQL_ADMIN_SECRET=pokt_admin_secret
      
      # Admin Configuration
      - ADMIN_EMAIL=admin@pokt.ai
      - ADMIN_PASSWORD=dev_admin_password
      - ADMIN_KEY=dev_admin_key
      
      # Monitoring and Analytics (DISABLED for development)
      - SENTRY_DSN=dev_sentry_dsn
      - UPSTASH_REDIS_REST_URL=http://localhost:3001/mock-redis
      - UPSTASH_REDIS_REST_TOKEN=dev_redis_token
      - MAILJET_API_KEY=dev_mailjet_api_key
      - MAILJET_API_SECRET=dev_mailjet_api_secret
      
      # Backend Configuration (DISABLED for development)
      - PORTAL_BACKEND_URL=http://localhost:3001/mock-backend
      - PORTAL_GRAPHQL_URL=http://localhost:3001/mock-graphql
      
    volumes:
      - ./public:/app/public
      - .:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
      hasura:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    command: ["pnpm", "exec", "remix", "vite:dev"]
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.poktportal-dev.rule=Host(`pokt.ai`)"
      - "traefik.http.routers.poktportal-dev.entrypoints=websecure"
      - "traefik.http.routers.poktportal-dev.tls.certresolver=https-resolver"
      - "traefik.http.services.poktportal-dev.loadbalancer.server.port=3000"

networks:
  default:
    name: poktia
    external: true

volumes:
  postgres_data_dev:
    driver: local
  redis_data_dev:
    driver: local 