openapi: "3.0.0"
info:
  title: Portal DWH Service API
  version: "1.0"
  description: Service that provides data from DWH to the Portal
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0

servers:
  - url: /api/v1
security:
  - apiKey: []

paths:
  /healthcheck:
    get:
      tags:
        - "system"
      summary: Check the health of the service.
      responses:
        "200":
          description: The service is healthy.
        "503":
          description: The service is not healthy.

  /analytics/relays/{category}/{query_type}/{group_by}:
    get:
      tags:
        - "user"
      summary: Relays analytics retrieve aggregated values of a chosen metric category between selected dates.
      parameters:
        - name: from
          in: query
          required: true
          schema:
            type: string
            format: date
        - name: to
          in: query
          required: true
          schema:
            type: string
            format: date
        - name: category
          in: path
          required: true
          description: The category of a metric to get insights of.
          schema:
            type: string
            enum:
              - transactions
              - errors
        - name: query_type
          in: path
          required: true
          description: Full query returns all the data, reduced query returns only the aggregated values.
          schema:
            type: string
            enum:
              - full
              - reduced
        - name: group_by
          in: path
          required: true
          description: The category of a metric to get insights of.
          schema:
            type: string
            enum:
              - day
              - none
        - name: account_id
          in: query
          required: true
          schema:
            type: array
            items:
              type: string
        - name: portal_application_id
          in: query
          required: false
          schema:
            type: array
            items:
              type: string
        - name: chain_id
          in: query
          required: false
          schema:
            type: array
            items:
              type: string
        - name: chain_method
          in: query
          required: false
          schema:
            type: array
            items:
              type: string
        - name: pagination
          in: query
          required: false
          schema:
            $ref: "#/components/schemas/Pagination"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseAnalyticsRelays"
        "204":
          description: No content
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "404":
          $ref: "#/components/responses/NotFound"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /logs:
    get:
      tags:
        - "user"
      summary: Retrieve application error messages.
      parameters:
        - name: portal_application_id
          in: query
          required: true
          schema:
            type: array
            items:
              type: string
        - name: pagination
          in: query
          required: false
          schema:
            $ref: "#/components/schemas/Pagination"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseLogs"
        "204":
          description: No content
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "404":
          $ref: "#/components/responses/NotFound"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  responses:
    Unauthorized:
      description: Unauthorized request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"

  securitySchemes:
    apiKey:
      type: apiKey
      name: Portal-DWH-Service-Api-Key
      in: header

  schemas:
    Error:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string

    MetaQueryAnalyticsRelays:
      type: object
      properties:
        from:
          type: string
          format: date
        to:
          type: string
          format: date
        account_id:
          type: array
          items:
            type: string
        portal_application_id:
          type: array
          items:
            type: string
        chain_id:
          type: array
          items:
            type: string
        chain_method:
          type: array
          items:
            type: string

    MetaPathAnalyticsRelays:
      type: object
      properties:
        category:
          type: string
          enum:
            - transactions
            - errors
        query_type:
          type: string
          enum:
            - full
            - reduced
        group_by:
          type: string
          enum:
            - day
            - none

    MetaLogs:
      type: object
      properties:
        portal_application_id:
          type: array
          items:
            type: string

    Pagination:
      type: object
      properties:
        limit:
          type: integer
          format: int32
          default: 100
          minimum: 10
          maximum: 1000
        after_id:
          type: integer
          format: int32

    AnalyticsRelaysTransactionsFull:
      type: object
      properties:
        from:
          type: string
          format: date
        to:
          type: string
          format: date
        account_id:
          type: string
        portal_application_id:
          type: string
        chain_id:
          type: string
        chain_method:
          type: string
        rate_success:
          type: number
          format: float
        count_total:
          type: integer
        avg_latency:
          type: number
          format: float

    AnalyticsRelaysTransactionsReduced:
      type: object
      properties:
        from:
          type: string
          format: date
        to:
          type: string
          format: date
        rate_success:
          type: number
          format: float
        count_total:
          type: integer
        avg_latency:
          type: number
          format: float

    AnalyticsRelaysTransactionsReducedGroupByDay:
      type: object
      properties:
        date:
          type: string
          format: date
        rate_success:
          type: number
          format: float
        count_total:
          type: integer
        avg_latency:
          type: number
          format: float

    AnalyticsRelaysErrorsFull:
      type: object
      properties:
        from:
          type: string
          format: date
        to:
          type: string
          format: date
        account_id:
          type: string
        portal_application_id:
          type: string
        chain_id:
          type: string
        chain_method:
          type: string
        rate_success:
          type: number
          format: float
        count_total:
          type: integer
        avg_latency:
          type: number
          format: float

    AnalyticsRelaysErrorsReduced:
      type: object
      properties:
        from:
          type: string
          format: date
        to:
          type: string
          format: date
        error_type:
          type: string
        error_name:
          type: string
        count_total:
          type: integer

    AnalyticsRelaysErrorsReducedGroupByDay:
      type: object
      properties:
        date:
          type: string
          format: date
        error_type:
          type: string
        error_name:
          type: string
        count_total:
          type: integer

    Logs:
      type: object
      properties:
        ts:
          type: string
          format: timestamp
        portal_application_id:
          type: string
        chain_id:
          type: string
        chain_method:
          type: string
        error_type:
          type: string
        error_name:
          type: string
        error_message:
          type: string

    ResponseAnalyticsRelays:
      type: object
      properties:
        meta:
          type: object
          properties:
            query:
              $ref: "#/components/schemas/MetaQueryAnalyticsRelays"
            path:
              $ref: "#/components/schemas/MetaPathAnalyticsRelays"
        data:
          type: array
          items:
            oneOf:
              - $ref: "#/components/schemas/AnalyticsRelaysTransactionsFull"
              - $ref: "#/components/schemas/AnalyticsRelaysTransactionsReduced"
              - $ref: "#/components/schemas/AnalyticsRelaysTransactionsReducedGroupByDay"
              - $ref: "#/components/schemas/AnalyticsRelaysErrorsFull"
              - $ref: "#/components/schemas/AnalyticsRelaysErrorsReduced"
              - $ref: "#/components/schemas/AnalyticsRelaysErrorsReducedGroupByDay"
              - $ref: "#/components/schemas/Logs"

    ResponseLogs:
      type: object
      properties:
        meta:
          $ref: "#/components/schemas/MetaLogs"
        data:
          type: array
          items:
            $ref: "#/components/schemas/Logs"

tags:
  - name: "system"
    description: "Operations related to api-server"
  - name: "user"
    description: "Operations related to individual portal users and their applications"
  - name: "product"
    description: "Operations related to the portal data as a whole"
