schema: http://localhost:8080/v1/graphql
documents: "./app/models/portal/*.graphqls"
generates:
  ./app/models/portal/sdk.ts:
    overwrite: true
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-graphql-request"
    config:
      headers:
        - "x-hasura-admin-secret: pokt_admin_secret"
